### ISSUE TITLE
[question] Why it is an empty repo?

### ISSUE THREAD

**Issue by Freed-Wu** [YuxuanZuo/android_device_oppo_PBCM10#1]

**Comment by YuxuanZuo** [comment]
I have tried to merge twrp device trees of all oppo sdm660 models, but I failed because of some blobs conflicts. So there is this empty repo XD

**Comment by YuxuanZuo** [comment]
If you are interested in porting twrp to your device, you can refer to the following repos:
https://github.com/YuxuanZuo/android_device_oppo_R11s
https://github.com/YuxuanZuo/android_device_oppo_sdm660-common
hope this will help you :)

**Comment by Freed-Wu** [comment]
Thanks.
BTW, your homepage <https://zuoyx.xyz> seems to be broken. :smile:
